### ISSUE TITLE
Running Demo

### ISSUE THREAD

**Issue by ghost** [samihormi/Multi-Camera-Person-Tracking-and-Re-Identification#3]
Hello,

Thank you for the repo. It is a helpful one. I'm trying to run the demo and have followed the instructions and ran into the error 

model_config = json.loads(model_config.decode('utf-8'))
'AttributeError: 'str' object has no attribute 'decode'' where the mode

The model path is as mentioned in /model_data/models/yolo3.h5.

Any possible reason for the error that you can point ?

**Comment by samihormi** [comment]
Hi there,

I honestly have never encountered this error, perhaps if you could show me the full error log I might be able to help.
(also make sure you download one of the ReID models(.pth) and place it in /model_data/models/ )

**Comment by 5875616E** [comment]
Solution: pip install h5py==2.10.0

**Comment by gayatriprasad** [comment]
Hey ! Sorry have been busy with other project and could not update the issue. Will try to let you know soon.
